services:
  carina:
    container_name: carina
    ports:
      - 60006:8906
    volumes:
      - ~/Desktop/docker/universe/carina:/proj
    working_dir: /proj/
    image: openjdk:11
    command: java -jar ser.jar --spring.config.location=optional:classpath:/,optional:classpath:/config/,optional:file:./,optional:file:./config/
    depends_on:
      - redis
  pgsql:
    container_name: pgsql
    ports:
      - 5432:5432
    volumes:
      - ~/Desktop/docker/pgsql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
    image: postgres
  redis:
    container_name: redis
    ports:
      - 6379:6379
    image: redis

  pgadmin:
    container_name: pgadmin
    ports:
      - 5433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: chengwei.ou.dora@gmail.com
      PGADMIN_DEFAULT_PASSWORD: aaa
    image: dpage/pgadmin4
