server:
  port: 55555
  servlet:
    context-path: /carina

spring:
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:postgresql://127.0.0.1/universe?currentSchema=carina
    username: postgres
    password: 123456

jwt:
  issuer: o
  sign: andromeda
  expMinute: 10
  refreshExpMinute: 600

site:
  andromeda: http://127.0.0.1:60002/andromeda

proj:
  serverHistory: false