server:
  port: 8906

spring:
  datasource:
    url: jdbc:postgresql://pgsql/universe?currentSchema=carina
    username: postgres
    password: 123456

jwt:
  issuer: o
  # use sign or the rsa path
  sign: andromeda
  # use this or the rsa path
  rsaPrivatePath: config/jwt-private.pem
  rsaPublicPath: config/jwt-public.pem
  expMinute: 10
  refreshExpMinute: 60

site:
  andromeda: http://andromeda:8906/andromeda

proj:
  serverHistory: false
